# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
#
# travis-ci.org specification for config-cpp
# 
language: cpp
compiler:
  - gcc
  # - clang
os:
  - linux

sudo: required
dist: trusty

before_install:

  # Install lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

  # Install googletest
  - wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz -O /tmp/gtest.tar.gz
  - tar zxf /tmp/gtest.tar.gz
  - pushd googletest-* && mkdir build && cd build && cmake .. && sudo make install && popd

  # Install json
  - wget https://github.com/nlohmann/json/archive/v3.5.0.tar.gz -O /tmp/json.tar.gz
  - tar zxf /tmp/json.tar.gz
  - pushd json-* && mkdir build && cd build && cmake -DJSON_BuildTests=OFF .. && sudo make install && popd

  # Install yaml-cpp
  - wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz -O /tmp/yaml.tar.gz
  - tar zxf /tmp/yaml.tar.gz
  - pushd yaml-* && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DYAML_CPP_BUILD_TESTS=OFF .. && sudo make install && popd

script:
  - mkdir build
  - cd build
  - cmake -DYAML_SUPPORT=ON -DJSON_SUPPORT=ON -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$PWD/.. -DBUILD_TESTS=ON .. && make
  - ./test/ConfigCppTests

# after_success:
#   - lcov --directory . --capture --output-file coverage.info # capture coverage info
#   - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
#   - lcov --list coverage.info # debug before upload
#   - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveral

