name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Use container with docker installed
    container: 
      image: catthehacker/ubuntu:act-latest
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        config:
          - { name: g++13, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/gcc, cxx: /usr/bin/g++, build_type: Debug, cppstd: 17 }
          - { name: g++13, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/gcc, cxx: /usr/bin/g++, build_type: Release, cppstd: 17 }
          - { name: clang16, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/clang, cxx: /usr/bin/clang++, build_type: Debug, cppstd: 17 }
          - { name: clang16, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/clang, cxx: /usr/bin/clang++, build_type: Release, cppstd: 17 }
          - { name: asan, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/gcc, cxx: /usr/bin/g++, build_type: asan, cppstd: 17 }
          - { name: tsan, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/gcc, cxx: /usr/bin/g++, build_type: tsan, cppstd: 17 }
          - { name: ubsan, image: fir.love.io:3005/amd64/config-cpp-gcc1311, cc: /usr/bin/gcc, cxx: /usr/bin/g++, build_type: ubsan, cppstd: 17 }
          - { name: g++8.4.0, image: fir.love.io:3005/amd64/config-cpp-gcc840, cc: /opt/gcc840/bin/gcc, cxx: /opt/gcc840/bin/g++, build_type: Debug, cppstd: 14 }
          - { name: g++8.4.0, image: fir.love.io:3005/amd64/config-cpp-gcc840, cc: /opt/gcc840/bin/gcc, cxx: /opt/gcc840/bin/g++, build_type: Debug, cppstd: 14 }
          - { name: g++10.3.0, image: fir.love.io:3005/amd64/config-cpp-gcc1030, cc: /opt/gcc1030/bin/gcc, cxx: /opt/gcc1030/bin/g++, build_type: Debug, cppstd: 14 }
          - { name: g++11.3.0, image: fir.love.io:3005/amd64/config-cpp-gcc1130, cc: /opt/gcc1130/bin/gcc, cxx: /opt/gcc1130/bin/g++, build_type: Debug, cppstd: 14 }
          - { name: g++12.3.0, image: fir.love.io:3005/amd64/config-cpp-gcc1230, cc: /opt/gcc1230/bin/gcc, cxx: /opt/gcc1230/bin/g++, build_type: Debug, cppstd: 20 }

    name: "${{ matrix.config.name}} (C++${{ matrix.config.cppstd }}, ${{ matrix.config.build_type }})"
    steps:
      - uses: actions/checkout@v3
      - name: Build 
        uses: https://github.com/addnab/docker-run-action@v3
        with:
          image: ${{ matrix.config.image }}
          options: --rm --volumes-from=${{ env.JOB_CONTAINER_NAME }}
          run: |
            cd ${{ gitea.workspace }}
            ./build.sh -cc=${{ matrix.config.cc }} --cxx=${{ matrix.config.cxx }} --cmake="-DCMAKE_BUILD_TYPE=${{ matrix.config.cppstd }} -DCMAKE_CXX_STD=${{ matrix.config.cppstd }}"
