---
# Test updates to an existing ConfigMap mounted by a pod
# use `kubectl replace -f configmap.yaml to apply the change
apiVersion: v1
kind: ConfigMap
metadata:
  name: configcpp
  namespace: default
data:
  config.json: |
    {
      "new1": "blah1",
      "new2": "blah2",
      "new3": "blah3"
    }
