---
resources:
- name: config-cpp-git
  type: git
  icon: github
  source:
    uri: https://fir.love.io:3000/CJLove/config-cpp

jobs:
- name: set-pipeline
  public: true
  plan:
  - get: config-cpp-git
    trigger: true
  - set_pipeline: config-cpp
    file: config-cpp-git/ci/pipeline.yml
# Build using current gcc and clang and fail fast
- name: build-current
  public: true
  plan:
  - get: config-cpp-git
    passed: [ set-pipeline ]
    trigger: true
  - in_parallel:
    - task: gcc13_1_1
      file: config-cpp-git/ci/gcc1311.yml
    - task: clang
      file: config-cpp-git/ci/clang.yml
# Build different combinations of json/yaml/toml support
- name: build-options
  public: true
  plan:
  - get: config-cpp-git
    passed: [ build-current ]
    trigger: true
  - in_parallel:
    - task: yaml-only
      file: config-cpp-git/ci/yaml.yml
    - task: json-only
      file: config-cpp-git/ci/json.yml
    - task: toml-only
      file: config-cpp-git/ci/toml.yml
# Build using broader matrix of compilers
- name: build-matrix
  public: true
  plan:  
  - get: config-cpp-git
    passed: [ build-options ]
    trigger: true
  - in_parallel:
    - task: gcc12_3_0
      file: config-cpp-git/ci/gcc1230.yml
    - task: gcc11_3_0
      file: config-cpp-git/ci/gcc1130.yml
    - task: gcc10_3_0
      file: config-cpp-git/ci/gcc1030.yml
    - task: gcc9_4_0
      file: config-cpp-git/ci/gcc940.yml
    - task: gcc8_4_0
      file: config-cpp-git/ci/gcc840.yml
    - task: gcc_7_4_0
      file: config-cpp-git/ci/gcc740.yml
    - task: gcc_6_5_0
      file: config-cpp-git/ci/gcc650.yml
# Build and test using sanitizers
- name: sanitizers
  public: true
  plan:
  - get: config-cpp-git
    passed: [ build-matrix ]
    trigger: true
  - in_parallel:
    - task: asan
      file: config-cpp-git/ci/asan.yml
      privileged: true
    - task: tsan
      file: config-cpp-git/ci/tsan.yml
      privileged: true

        
