name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - { compiler: gcc, version: 8, build_type: Release, cppstd: 14 }
#          - { compiler: gcc, version: 11, build_type: Debug, cppstd: 20 }
#          - { compiler: gcc, version: 12, build_type: Release, cppstd: 20 }
#          - { compiler: clang, version: 10, build_type: Release, cppstd: 14 }
#         - { compiler: clang, version: 10, build_type: Debug, cppstd: 17 }
#         - { compiler: clang, version: 12, build_type: Debug, cppstd: 17 }
          - { compiler: clang, version: 15, build_type: Release, cppstd: 14 }
    container:
      image: ${{ matrix.config.compiler == 'clang' && 'teeks99/clang-ubuntu' || matrix.config.compiler }}:${{ matrix.config.version }}
    name: "${{ matrix.config.compiler}} ${{ matrix.config.version }} (C++${{ matrix.config.cppstd }}, ${{ matrix.config.build_type }})"
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: |
          apt-get update && apt-get install -y curl git
          CMAKE_VERSION="3.24.2"
          curl -sSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh -o install-cmake.sh
          chmod +x install-cmake.sh
          ./install-cmake.sh --prefix=/usr/local --skip-license
      - name: Setup Compiler
        if: matrix.config.compiler == 'clang'
        run: |
          if [[ "${{ matrix.config.version }}" -ge 4 ]]; then
            scripts/ci_setup_clang.sh "${{ matrix.config.version }}"
            echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          fi
          echo "CC=clang-${{ matrix.config.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.config.version }}" >> $GITHUB_ENV
      - name: Dependencies
        run: |
          # Install json
          wget https://github.com/nlohmann/json/archive/v3.11.2.tar.gz -O /tmp/json.tar.gz
          tar zxf /tmp/json.tar.gz
          pushd json-* && mkdir build && cd build && cmake -DJSON_BuildTests=OFF .. && sudo make install && popd
          # Install yaml-cpp
          wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.7.0.tar.gz -O /tmp/yaml.tar.gz
          tar zxf /tmp/yaml.tar.gz
          pushd yaml-* && mkdir build && cd build && cmake -DYAML_BUILD_SHARED_LIBS=ON -DYAML_CPP_BUILD_TESTS=OFF .. && sudo make install && popd
          # Install cxxopts
          wget https://github.com/jarro2783/cxxopts/archive/v2.2.1.tar.gz -O /tmp/cxxopts.tar.gz
          tar zxf /tmp/cxxopts.tar.gz
          pushd cxxopts-* && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && sudo make install && popd
          wget https://github.com/ToruNiina/toml11/archive/v3.7.1.tar.gz -O /tmp/toml11.tar.gz
          # Install toml11
          tar zxf /tmp/toml11.tar.gz
          pushd toml11-* && mkdir build && cd build && cmake -Dtoml11_BUILD_TEST=OFF .. && sudo make install && popd

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_CXX_STANDARD=${{ matrix.config.cppstd }} \
            -DBUILD_EXAMPLES=${{ matrix.config.examples || 'ON' }} \
            -DYAML_SUPPORT=ON \
            -DJSON_SUPPORT=ON \
            -DTOML_SUPPORT=ON \
            -DBUILD_TESTS=ON 
          make -j2
          ctest -j2 --output-on-failure